export default {
  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_ERROR: "FETCH_POST_ERROR",
  DELETED_POST_START: "DELETED_POST_START",
  DELETED_POST_SUCCESS: "DELETED_POST_SUCCESS",
  DELETED_POST_ERROR: "DELETED_POST_ERROR",
  ADD_POST_START: "ADD_POST_START",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR",
  CHANGE_FILTER_VALUE: "CHANGE_FILTER_VALUE",
  EMPTY_FILTER_VALUE: "EMPTY_FILTER_VALUE"
};
